name: Tests

on:
  push:
    branches: '*'
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x, 18.x]

    steps:
    - name: Checkout repository
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
    run: |
        cd client
        npm install

    - name: Run tests
    run: |
        cd client
        npm run test:unit
